
const RESPONSE_CODE_SUCCESS = '0'
const RESPONSE_CODE_UNPROCESSABLE = '1'
const RESPONSE_SUCCESS = 'Success'
const REQUEST_BODY = 'body'

module.exports = {
  RESPONSE_CODE_SUCCESS,
  RESPONSE_CODE_UNPROCESSABLE,
  RESPONSE_SUCCESS,
  REQUEST_BODY
}
